spring:
  application:
    name: app
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true

jwt:
  header: Authorization
  issuer: jjbin
  secret: tCfj2cTfEvyAYeA+vJKihHb7t3Tt0NQZeJnvFkPbKtU=
  expiry-seconds: 3600
