spring:
  application:
    name: app
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
#    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 30s
      timeout: 10s

jwt:
  header: Authorization
  refresh-header: Refresh
  scheme: bearer
  issuer: jjbin
  secret: tCfj2cTfEvyAYeA+vJKihHb7t3Tt0NQZeJnvFkPbKtU=
  expiry-seconds: 3600
  refresh-expiry-seconds: 259200
