spring:
  application:
    name: appsecurity
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
#    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 30s
      timeout: 10s


auth:
  scheme: bearer
  header: Authorization

jwt:
  issuer: jjbin
  secret: tCfj2cTfEvyAYeA+vJKihHb7t3Tt0NQZeJnvFkPbKtU=
  expiry-seconds: 3600
  refresh-expiry-seconds: 259200
logging:
  level:
    root: debug
